[package]
name = "theme-orbit"
version = "0.1.0"
edition = "2024"
license = "BSD-3-Clause"

[workspace]

[lib]
name = "orbit"
crate-type = ["cdylib"]

[dependencies]
weasel-wasm-sdk = { path = "../sdk-rust" }

[build-dependencies]
png = "0.18"
serde_json = "1"

[profile.release]
panic = "abort"
lto = true
opt-level = "s"
strip = true
