/// Shared native projection for D2D candidate themes.
pub fn generate() {
    let out = std::path::PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));
    windows_bindgen::builder()
        .input_default()
        .output(out.join("d2d-bindings.rs"))
        .filters([
            "Windows.Win32.GetMessageW", "Windows.Win32.TranslateMessage", "Windows.Win32.DispatchMessageW",
            "Windows.Win32.IsDialogMessageW", "Windows.Win32.PostMessageW",
            "Windows.Win32.EnableWindow", "Windows.Win32.SetWindowTextW", "Windows.Win32.SetFocus",
            "Windows.Win32.MessageBoxW", "Windows.Win32.MB_OK", "Windows.Win32.MB_ICONERROR",
            "Windows.Win32.WS_OVERLAPPEDWINDOW", "Windows.Win32.WS_VISIBLE", "Windows.Win32.WS_CHILD",
            "Windows.Win32.WS_TABSTOP", "Windows.Win32.WS_EX_CONTROLPARENT",
            "Windows.Win32.WM_COMMAND", "Windows.Win32.WM_APP", "Windows.Win32.WM_DESTROY",
            "Windows.Win32.COLOR_BTNFACE", "Windows.Win32.GetSysColorBrush",
            "Windows.Win32.WM_SETFONT", "Windows.Win32.GetStockObject", "Windows.Win32.DEFAULT_GUI_FONT",
            "Windows.Win32.SetThreadDpiAwarenessContext", "Windows.Win32.DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2",
            "Windows.Win32.MonitorFromWindow", "Windows.Win32.MONITOR_DEFAULTTOPRIMARY", "Windows.Win32.GetMonitorInfoW",

            "Windows.Win32.D2D1CreateFactory", "Windows.Win32.DWriteCreateFactory",
            "Windows.Win32.ID2D1Factory::CreateHwndRenderTarget", "Windows.Win32.ID2D1HwndRenderTarget::Resize",
            "Windows.Win32.ID2D1SolidColorBrush::SetColor", "Windows.Win32.IDWriteFactory::{CreateTextFormat,CreateTextLayout}",
            "Windows.Win32.IDWriteTextFormat::{SetTextAlignment,SetParagraphAlignment,SetWordWrapping}",
            "Windows.Win32.IDWriteTextLayout::GetMetrics",
            "Windows.Win32.IDWriteTextLayout::HitTestTextPosition",
            "Windows.Win32.ID2D1RenderTarget::{DrawTextLayout,PushAxisAlignedClip,PopAxisAlignedClip}",
            "Windows.Win32.D2D1_ANTIALIAS_MODE",
            "Windows.Win32.ID2D1RenderTarget::{SetTextAntialiasMode,SetAntialiasMode}",
            "Windows.Win32.D2D1_TEXT_ANTIALIAS_MODE",
            "Windows.Win32.ID2D1RenderTarget::{SetDpi,CreateSolidColorBrush,BeginDraw,EndDraw,Clear,FillRectangle,DrawText}",
            "Windows.Win32.D2D1_FACTORY_TYPE", "Windows.Win32.D2D1_PRESENT_OPTIONS",
            "Windows.Win32.D2D1_DRAW_TEXT_OPTIONS", "Windows.Win32.D2D1_ALPHA_MODE",
            "Windows.Win32.D2DERR_RECREATE_TARGET",
            "Windows.Win32.E_UNEXPECTED",
            "Windows.Win32.DWRITE_FACTORY_TYPE", "Windows.Win32.DWRITE_FONT_WEIGHT",
            "Windows.Win32.DWRITE_FONT_STYLE", "Windows.Win32.DWRITE_FONT_STRETCH",
            "Windows.Win32.DWRITE_TEXT_ALIGNMENT", "Windows.Win32.DWRITE_PARAGRAPH_ALIGNMENT",
            "Windows.Win32.DWRITE_WORD_WRAPPING", "Windows.Win32.DWRITE_MEASURING_MODE",
            "Windows.Win32.BeginPaint", "Windows.Win32.EndPaint", "Windows.Win32.InvalidateRect",
            "Windows.Win32.GetModuleHandleW", "Windows.Win32.RegisterClassW",
            "Windows.Win32.GetClassInfoW", "Windows.Win32.LoadCursorW", "Windows.Win32.IDC_ARROW",
            "Windows.Win32.LoadIconW",
            "Windows.Win32.SW_SHOW",
            "Windows.Win32.WS_SYSMENU",
            "Windows.Win32.CreateWindowExW", "Windows.Win32.DestroyWindow",
            "Windows.Win32.DefWindowProcW", "Windows.Win32.GetWindowLongPtrW",
            "Windows.Win32.SetWindowLongPtrW", "Windows.Win32.GWLP_USERDATA",
            "Windows.Win32.GetClientRect", "Windows.Win32.SetWindowPos", "Windows.Win32.ShowWindow",
            "Windows.Win32.GetDpiForWindow", "Windows.Win32.SetCapture", "Windows.Win32.GetCapture",
            "Windows.Win32.ReleaseCapture", "Windows.Win32.TrackMouseEvent", "Windows.Win32.TME_LEAVE",
            "Windows.Win32.SetTimer", "Windows.Win32.KillTimer",
            "Windows.Win32.WS_POPUP", "Windows.Win32.WS_EX_TOPMOST", "Windows.Win32.WS_EX_TOOLWINDOW",
            "Windows.Win32.WS_EX_NOACTIVATE", "Windows.Win32.HWND_TOPMOST", "Windows.Win32.SWP_NOACTIVATE",
            "Windows.Win32.SW_SHOWNOACTIVATE", "Windows.Win32.SW_HIDE",
            "Windows.Win32.WM_NCCREATE", "Windows.Win32.WM_NCDESTROY", "Windows.Win32.WM_PAINT",
            "Windows.Win32.WM_ERASEBKGND", "Windows.Win32.WM_SIZE", "Windows.Win32.WM_DPICHANGED",
            "Windows.Win32.WM_LBUTTONDOWN", "Windows.Win32.WM_LBUTTONUP", "Windows.Win32.WM_MOUSEMOVE",
            "Windows.Win32.WM_MOUSELEAVE", "Windows.Win32.WM_CAPTURECHANGED", "Windows.Win32.WM_CANCELMODE",
            "Windows.Win32.WM_MOUSEACTIVATE", "Windows.Win32.MA_NOACTIVATE", "Windows.Win32.WM_TIMER",
            "Windows.Win32.WM_CLOSE", "Windows.Win32.PostQuitMessage",
            "Windows.Win32.WM_SETICON", "Windows.Win32.ICON_SMALL", "Windows.Win32.ICON_BIG",
            "Windows.Win32.SendMessageW",
            "Windows.Win32.CREATESTRUCTW",
        ])
        .write();
    println!("cargo:rerun-if-changed=build_d2d.rs");
}
