[package]
name = "weasel-renderer"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
weasel-common = { path = "../common" }
tokio = { version = "1", features = ["io-util", "macros", "net", "rt", "sync", "time"] }
windows-core = "0.100.0"
windows-numerics = "0.100.0"
windows-collections = "0.100.0"
windows-reference = "0.100.0"
windows-time = "0.100.0"
windows-version = "0.100.0"

windows-strings = "0.100.0"

[build-dependencies]
embed-resource = "3"
windows-bindgen = "0.100.0"
windows-rdl = "0.100.0"
