[package]
name = "weasel-renderer"
version = "0.1.4"
edition = "2024"
license.workspace = true

[dependencies]
serde_json = "1"
serde = "1"
weasel-theme-api = { path = "../theme-api" }
weasel-theme-support = { path = "../themes/support" }
weasel-common = { path = "../common" }
tokio = { version = "1", features = ["io-util", "macros", "net", "rt", "sync", "time"] }
windows-core = "0.100.0"

windows-strings = "0.100.0"

[build-dependencies]
embed-resource = "3"
